<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <DebugType>embedded</DebugType>
    <Configurations>Release;Debug</Configurations>
    <AssemblyName>ScenarioCreatorServer.net</AssemblyName>
    <TargetName>$(AssemblyName)</TargetName>
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>SERVER</DefineConstants>
	<LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\SharedClasses\ConfigManager.cs" Link="ConfigManager.cs" />
    <Compile Include="..\SharedClasses\Globals.cs" Link="Globals.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    
    <PackageReference Include="CitizenFX.Core.Server" Version="1.0.6335">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\dependencies\shared\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="config\addons.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config\locations.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config\permissions.cfg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="storage.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="System.Numerics.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="H:\Servers\fivem_empty_server\resources\scenario-creator\ScenarioCreatorServer\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="H:\Servers\fivem_empty_server\resources\scenario-creator\ScenarioCreatorServer\.editorconfig" />
  </ItemGroup>

</Project>
