<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <DebugType>embedded</DebugType>
    <Configurations>Release;Debug</Configurations>
    <AssemblyName>ScenarioCreator.net</AssemblyName>
    <TargetName>$(AssemblyName)</TargetName>
    <OutputPath>..\..\build\</OutputPath>
    <DefineConstants>CLIENT</DefineConstants>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="data\**" />
    <EmbeddedResource Remove="data\**" />
    <None Remove="data\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\SharedClasses\Scenario.cs" Link="Scenario.cs" />
    <Compile Include="..\SharedClasses\ScenarioPed.cs" Link="ScenarioPed.cs" />
    <Compile Include="..\SharedClasses\ScenarioProp.cs" Link="ScenarioProp.cs" />
    <Compile Include="..\SharedClasses\ScenarioVehicle.cs" Link="ScenarioVehicle.cs" />
    <Compile Include="..\SharedClasses\ConfigManager.cs" Link="ConfigManager.cs" />
    <Compile Include="..\SharedClasses\Globals.cs" Link="Globals.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MenuAPI.FiveM" Version="3.2.2" />

    <Reference Include="Microsoft.CSharp" />
    
    <PackageReference Include="CitizenFX.Core.Client" Version="1.0.6370">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\dependencies\shared\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>

  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if exist &quot;$(SolutionDir)\postbuild.cmd&quot; &quot;$(SolutionDir)postbuild.cmd&quot;" />
  </Target>

  <ItemGroup>
    <EditorConfigFiles Remove="H:\Servers\fivem_empty_server\resources\scenario-creator\ScenarioCreator\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="H:\Servers\fivem_empty_server\resources\scenario-creator\ScenarioCreator\.editorconfig" />
  </ItemGroup>
</Project>
